import numpy as np
import pandas as pd
import joblib

from pathlib import Path


# ============================================================
# CONFIGURATION
# ============================================================

USER_ID = "USER_002"

TOP_N = 5

# Hybrid ranking weights
MODEL_WEIGHT = 0.70
VISUAL_WEIGHT = 0.30


# ============================================================
# PATHS
# ============================================================

CATALOGUE_PATH = Path(
    "data/catalogue/eyewear_catalogue.csv"
)

MODEL_PATH = Path(
    "models/recommendation/hybrid_model.joblib"
)

EMBEDDINGS_PATH = Path(
    "data/processed/eyewear/frame_embeddings.npy"
)

EMBEDDING_METADATA_PATH = Path(
    "data/processed/eyewear/frame_metadata.csv"
)

FEEDBACK_PATH = Path(
    "data/catalogue/feedback.csv"
)

VISUAL_PROFILE_PATH = Path(
    "data/processed/recommendations/user_visual_profile.csv"
)

OUTPUT_PATH = Path(
    "data/processed/recommendations/latest_recommendations.csv"
)


# ============================================================
# USER PROFILE
# ============================================================

USER_PROFILE = {
    "face_shape": "Round",
    "preferred_style": "Casual",
    "preferred_color": "Black",
    "preferred_frame_type": "Optical",
    "budget": 3000
}


# ============================================================
# FACE COMPATIBILITY RULES
# ============================================================

FACE_COMPATIBILITY_RULES = {

    "Heart": {
        "Rectangle": 0.85,
        "Cat Eye": 0.75,
        "Aviator": 0.90,
        "Geometric": 0.70,
        "Round": 0.80,
        "Square": 0.65,
        "Clubmaster": 0.85,
    },

    "Oblong": {
        "Rectangle": 0.85,
        "Cat Eye": 0.75,
        "Aviator": 0.90,
        "Geometric": 0.75,
        "Round": 0.90,
        "Square": 0.80,
        "Clubmaster": 0.85,
    },

    "Oval": {
        "Rectangle": 0.90,
        "Cat Eye": 0.85,
        "Aviator": 0.85,
        "Geometric": 0.85,
        "Round": 0.90,
        "Square": 0.85,
        "Clubmaster": 0.90,
    },

    "Round": {
        "Rectangle": 1.00,
        "Cat Eye": 0.75,
        "Aviator": 0.85,
        "Geometric": 0.90,
        "Round": 0.65,
        "Square": 0.90,
        "Clubmaster": 0.85,
    },

    "Square": {
        "Rectangle": 0.70,
        "Cat Eye": 0.85,
        "Aviator": 0.90,
        "Geometric": 0.80,
        "Round": 0.90,
        "Square": 0.70,
        "Clubmaster": 0.85,
    },
}


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_face_compatibility(
    face_shape,
    frame_shape
):
    """
    Return rule-based face/frame compatibility score.
    """

    return (
        FACE_COMPATIBILITY_RULES
        .get(face_shape, {})
        .get(frame_shape, 0.0)
    )


def load_feedback():
    """
    Load user interaction history.
    """

    if not FEEDBACK_PATH.exists():

        return pd.DataFrame(
            columns=[
                "user_id",
                "frame_id",
                "liked"
            ]
        )

    feedback = pd.read_csv(
        FEEDBACK_PATH
    )

    required_columns = {
        "user_id",
        "frame_id",
        "liked"
    }

    missing = (
        required_columns
        -
        set(feedback.columns)
    )

    if missing:

        raise ValueError(
            "feedback.csv is missing columns: "
            + str(sorted(missing))
        )

    feedback["user_id"] = (
        feedback["user_id"]
        .astype(str)
    )

    feedback["frame_id"] = (
        feedback["frame_id"]
        .astype(str)
    )

    feedback["liked"] = (
        pd.to_numeric(
            feedback["liked"],
            errors="coerce"
        )
        .fillna(0)
        .astype(int)
    )

    return feedback


def load_visual_scores():
    """
    Load the personalized visual preference
    scores generated by personalization_loop.py.
    """

    if not VISUAL_PROFILE_PATH.exists():

        return {}

    profile = pd.read_csv(
        VISUAL_PROFILE_PATH
    )

    required_columns = {
        "frame_id",
        "visual_preference_score"
    }

    if not required_columns.issubset(
        profile.columns
    ):

        raise ValueError(
            "user_visual_profile.csv must contain "
            "frame_id and visual_preference_score."
        )

    profile["frame_id"] = (
        profile["frame_id"]
        .astype(str)
    )

    profile[
        "visual_preference_score"
    ] = pd.to_numeric(
        profile[
            "visual_preference_score"
        ],
        errors="coerce"
    ).fillna(0.0)

    return dict(
        zip(
            profile["frame_id"],
            profile[
                "visual_preference_score"
            ]
        )
    )


def validate_model_features(model):
    """
    Verify that the trained sklearn model has
    the feature schema we expect.
    """

    expected_features = [
        "face_compatibility",
        "visual_preference_score",
        "style_match",
        "color_match",
        "frame_type_match"
    ]

    if not hasattr(
        model,
        "feature_names_in_"
    ):

        return expected_features

    actual_features = list(
        model.feature_names_in_
    )

    if actual_features != expected_features:

        raise ValueError(
            "\nModel feature mismatch.\n"
            f"Expected: {expected_features}\n"
            f"Model has: {actual_features}\n"
        )

    return expected_features


# ============================================================
# MAIN RECOMMENDER
# ============================================================

def main():

    print("\n==============================================")
    print("ML HYBRID EYEWEAR RECOMMENDER")
    print("==============================================")

    print(
        f"User: {USER_ID}"
    )


    # ========================================================
    # LOAD CATALOGUE
    # ========================================================

    if not CATALOGUE_PATH.exists():

        raise FileNotFoundError(
            f"Catalogue not found: {CATALOGUE_PATH}"
        )

    catalogue = pd.read_csv(
        CATALOGUE_PATH
    )


    required_catalogue_columns = [
        "frame_id",
        "brand",
        "frame_shape",
        "frame_color",
        "style",
        "frame_type",
        "material"
    ]


    missing_columns = [
        column
        for column in required_catalogue_columns
        if column not in catalogue.columns
    ]


    if missing_columns:

        raise ValueError(
            "Catalogue is missing columns: "
            + str(missing_columns)
        )


    print(
        f"Catalogue frames: {len(catalogue)}"
    )


    # ========================================================
    # LOAD MODEL
    # ========================================================

    if not MODEL_PATH.exists():

        raise FileNotFoundError(
            f"Model not found: {MODEL_PATH}"
        )

    model = joblib.load(
        MODEL_PATH
    )

    print(
        f"Model loaded: {MODEL_PATH}"
    )


    # ========================================================
    # VALIDATE MODEL
    # ========================================================

    model_features = (
        validate_model_features(
            model
        )
    )


    print(
        "\nModel features:"
    )

    print(
        model_features
    )


    # ========================================================
    # LOAD FEEDBACK
    # ========================================================

    feedback = load_feedback()


    user_feedback = feedback[
        feedback["user_id"] == USER_ID
    ].copy()


    liked_frames = set(
        user_feedback[
            user_feedback["liked"] == 1
        ]["frame_id"]
    )


    disliked_frames = set(
        user_feedback[
            user_feedback["liked"] == 0
        ]["frame_id"]
    )


    interacted_frames = (
        liked_frames
        |
        disliked_frames
    )


    # ========================================================
    # DISPLAY HISTORY
    # ========================================================

    print("\n==============================================")
    print("USER HISTORY")
    print("==============================================")


    print(
        "Liked:",
        sorted(liked_frames)
    )


    print(
        "Disliked:",
        sorted(disliked_frames)
    )


    print(
        "Previously interacted:",
        sorted(interacted_frames)
    )


    # ========================================================
    # LOAD VISUAL PREFERENCE
    # ========================================================

    visual_scores = (
        load_visual_scores()
    )


    # ========================================================
    # BUILD MODEL FEATURES
    # ========================================================

    feature_rows = []


    for _, frame in catalogue.iterrows():

        frame_id = str(
            frame["frame_id"]
        )


        # ----------------------------------------------------
        # Face compatibility
        # ----------------------------------------------------

        face_compatibility = (
            get_face_compatibility(
                USER_PROFILE["face_shape"],
                str(
                    frame["frame_shape"]
                )
            )
        )


        # ----------------------------------------------------
        # Style match
        # ----------------------------------------------------

        style_match = int(
            str(
                frame["style"]
            ).lower()
            ==
            str(
                USER_PROFILE["preferred_style"]
            ).lower()
        )


        # ----------------------------------------------------
        # Color match
        # ----------------------------------------------------

        frame_color = str(
            frame["frame_color"]
        ).lower()

        preferred_color = str(
            USER_PROFILE["preferred_color"]
        ).lower()


        color_match = int(
            preferred_color
            in
            frame_color
        )


        # ----------------------------------------------------
        # Frame type match
        # ----------------------------------------------------

        frame_type_match = int(
            str(
                frame["frame_type"]
            ).lower()
            ==
            str(
                USER_PROFILE["preferred_frame_type"]
            ).lower()
        )


        # ----------------------------------------------------
        # Visual preference
        # ----------------------------------------------------

        visual_preference_score = float(
            visual_scores.get(
                frame_id,
                0.0
            )
        )


        feature_rows.append(
            {
                "frame_id":
                    frame_id,

                "face_compatibility":
                    face_compatibility,

                "visual_preference_score":
                    visual_preference_score,

                "style_match":
                    style_match,

                "color_match":
                    color_match,

                "frame_type_match":
                    frame_type_match
            }
        )


    features_df = pd.DataFrame(
        feature_rows
    )


    # ========================================================
    # CREATE EXACT MODEL INPUT
    # ========================================================

    X = features_df[
        model_features
    ].copy()


    # ========================================================
    # MODEL PREDICTION
    # ========================================================

    if hasattr(
        model,
        "predict_proba"
    ):

        model_probability = (
            model.predict_proba(X)[:, 1]
        )

    else:

        model_probability = (
            model.predict(X)
        )


    features_df[
        "model_probability"
    ] = np.asarray(
        model_probability,
        dtype=float
    )


    # ========================================================
    # HYBRID SCORE
    # ========================================================

    features_df[
        "hybrid_score"
    ] = (

        MODEL_WEIGHT
        *
        features_df[
            "model_probability"
        ]

        +

        VISUAL_WEIGHT
        *
        features_df[
            "visual_preference_score"
        ]
    )


    # ========================================================
    # REMOVE PREVIOUSLY INTERACTED FRAMES
    # ========================================================

    recommendations = features_df[
        ~features_df[
            "frame_id"
        ].isin(
            interacted_frames
        )
    ].copy()


    # ========================================================
    # RANK
    # ========================================================

    recommendations = (
        recommendations
        .sort_values(
            by="hybrid_score",
            ascending=False
        )
        .head(TOP_N)
        .reset_index(
            drop=True
        )
    )


    # ========================================================
    # ADD CATALOGUE INFORMATION
    # ========================================================

    catalogue_display = catalogue[
        [
            "frame_id",
            "brand",
            "frame_shape",
            "frame_color",
            "style",
            "frame_type",
            "material"
        ]
    ].copy()


    recommendations = (
        recommendations.merge(
            catalogue_display,
            on="frame_id",
            how="left"
        )
    )


    # ========================================================
    # SAVE RESULTS
    # ========================================================

    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True
    )


    recommendations.to_csv(
        OUTPUT_PATH,
        index=False
    )


    # ========================================================
    # DISPLAY RECOMMENDATIONS
    # ========================================================

    print("\n==============================================")
    print("TOP PERSONALIZED RECOMMENDATIONS")
    print("==============================================")


    if recommendations.empty:

        print(
            "\nNo unseen frames are available."
        )

        print(
            "The user has interacted with every "
            "frame in the catalogue."
        )

    else:

        for index, row in (
            recommendations.iterrows()
        ):

            print(
                f"\n#{index + 1} "
                f"{row['frame_id']}"
            )

            print(
                f"Brand: {row['brand']}"
            )

            print(
                f"Shape: {row['frame_shape']}"
            )

            print(
                f"Color: {row['frame_color']}"
            )

            print(
                f"Style: {row['style']}"
            )

            print(
                f"Material: {row['material']}"
            )

            print(
                "Face compatibility: "
                f"{row['face_compatibility']:.4f}"
            )

            print(
                "Visual preference: "
                f"{row['visual_preference_score']:.4f}"
            )

            print(
                "ML like probability: "
                f"{row['model_probability']:.4f}"
            )

            print(
                "Hybrid score: "
                f"{row['hybrid_score']:.4f}"
            )


    # ========================================================
    # SAVE / STATUS
    # ========================================================

    print("\n==============================================")
    print("RECOMMENDATION COMPLETE")
    print("==============================================")


    print(
        f"Candidates evaluated: "
        f"{len(features_df)}"
    )


    print(
        f"Previously interacted: "
        f"{len(interacted_frames)}"
    )


    print(
        f"New recommendations: "
        f"{len(recommendations)}"
    )


    print(
        f"\nSaved to:\n{OUTPUT_PATH}"
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()